const columns = [
  { name: 'ID', uid: 'id', sortable: true },
  { name: 'NAME', uid: 'name', sortable: true },
  { name: 'EMAIL', uid: 'email', sortable: true },
  { name: 'ROLE', uid: 'role', sortable: true },
  { name: 'SET ROLE', uid: 'set role', sortable: false },
];

const users = [
  {
    id: 10000,
    name: 'Tony Reichert',
    role: 'USER',
    email: 'tony.reichert@example.com',
  },
  {
    id: 20000,
    name: 'Zoey Lang',
    role: 'PROGRAM HEAD',
    email: 'zoey.lang@example.com',
  },
  {
    id: 30000,
    name: 'Jane Fisher',
    role: 'LIBRARIAN',
    email: 'jane.fisher@example.com',
  },
  {
    id: 40000,
    name: 'William Howard',
    role: 'REGISTRAR',
    email: 'william.howard@example.com',
  },
  {
    id: 50000,
    name: 'Kristen Copper',
    role: 'GUIDANCE',
    email: 'kristen.cooper@example.com',
  },
  {
    id: 60000,
    name: 'Brian Kim',
    role: 'MIS',
    email: 'brian.kim@example.com',
  },
  {
    id: 70000,
    name: 'Michael Hunt',
    role: 'CASHIER',
    email: 'michael.hunt@example.com',
  },
  {
    id: 80000,
    name: 'Samantha Brooks',
    role: 'DISCIPLINE',
    email: 'samantha.brooks@example.com',
  },
  {
    id: 90000,
    name: 'Frank Harrison',
    role: 'USER',
    email: 'frank.harrison@example.com',
  },
  {
    id: 10010,
    name: 'Emma Adams',
    role: 'PURCHASING',
    email: 'emma.adams@example.com',
  },
  {
    id: 10011,
    name: 'Brandon Stevens',
    role: 'LIBRARIAN',
    email: 'brandon.stevens@example.com',
  },
  {
    id: 10012,
    name: 'Megan Richards',
    role: 'GUIDANCE',
    email: 'megan.richards@example.com',
  },
  {
    id: 10013,
    name: 'Oliver Scott',
    role: 'MIS',
    email: 'oliver.scott@example.com',
  },
  {
    id: 10014,
    name: 'Grace Allen',
    role: 'PROGRAM HEAD',
    email: 'grace.allen@example.com',
  },
  {
    id: 10015,
    name: 'Noah Carter',
    role: 'CASHIER',
    email: 'noah.carter@example.com',
  },
  {
    id: 10016,
    name: 'Ava Perez',
    role: 'USER',
    email: 'ava.perez@example.com',
  },
  {
    id: 10017,
    name: 'Liam Johnson',
    role: 'REGISTRAR',
    email: 'liam.johnson@example.com',
  },
  {
    id: 10018,
    name: 'Sophia Taylor',
    role: 'DISCIPLINE',
    email: 'sophia.taylor@example.com',
  },
  {
    id: 10019,
    name: 'Lucas Harris',
    role: 'PURCHASING',
    email: 'lucas.harris@example.com',
  },
  {
    id: 10020,
    name: 'Mia Robinson',
    role: 'USER',
    email: 'mia.robinson@example.com',
  },
  {
    id: 10021,
    name: 'Ella Martinez',
    role: 'GUIDANCE',
    email: 'ella.martinez@example.com',
  },
  {
    id: 10022,
    name: 'Ethan Anderson',
    role: 'LIBRARIAN',
    email: 'ethan.anderson@example.com',
  },
  {
    id: 10023,
    name: 'Avery Thomas',
    role: 'DISCIPLINE',
    email: 'avery.thomas@example.com',
  },
  {
    id: 10024,
    name: 'Isabella Jackson',
    role: 'USER',
    email: 'isabella.jackson@example.com',
  },
  {
    id: 10025,
    name: 'Mason White',
    role: 'MIS',
    email: 'mason.white@example.com',
  },
  {
    id: 10026,
    name: 'Harper Harris',
    role: 'CASHIER',
    email: 'harper.harris@example.com',
  },
  {
    id: 10027,
    name: 'Logan Martin',
    role: 'PROGRAM HEAD',
    email: 'logan.martin@example.com',
  },
  {
    id: 10028,
    name: 'Aria Garcia',
    role: 'REGISTRAR',
    email: 'aria.garcia@example.com',
  },
  {
    id: 10029,
    name: 'James Lee',
    role: 'USER',
    email: 'james.lee@example.com',
  },
  {
    id: 10030,
    name: 'Charlotte Clark',
    role: 'PURCHASING',
    email: 'charlotte.clark@example.com',
  },
  {
    id: 10031,
    name: 'Henry Lewis',
    role: 'GUIDANCE',
    email: 'henry.lewis@example.com',
  },
  {
    id: 10032,
    name: 'Amelia Walker',
    role: 'LIBRARIAN',
    email: 'amelia.walker@example.com',
  },
  {
    id: 10033,
    name: 'Jack Young',
    role: 'DISCIPLINE',
    email: 'jack.young@example.com',
  },
  {
    id: 10034,
    name: 'Scarlett Hall',
    role: 'USER',
    email: 'scarlett.hall@example.com',
  },
  {
    id: 10035,
    name: 'Leo Allen',
    role: 'MIS',
    email: 'leo.allen@example.com',
  },
  {
    id: 10036,
    name: 'Chloe King',
    role: 'CASHIER',
    email: 'chloe.king@example.com',
  },
  {
    id: 10037,
    name: 'Benjamin Wright',
    role: 'PROGRAM HEAD',
    email: 'benjamin.wright@example.com',
  },
  {
    id: 10038,
    name: 'Sofia Scott',
    role: 'REGISTRAR',
    email: 'sofia.scott@example.com',
  },
  {
    id: 10039,
    name: 'Lucas Green',
    role: 'USER',
    email: 'lucas.green@example.com',
  },
  {
    id: 10040,
    name: 'Zoe Adams',
    role: 'PURCHASING',
    email: 'zoe.adams@example.com',
  },
  {
    id: 10041,
    name: 'Daniel Nelson',
    role: 'GUIDANCE',
    email: 'daniel.nelson@example.com',
  },
  {
    id: 10042,
    name: 'Lily Baker',
    role: 'LIBRARIAN',
    email: 'lily.baker@example.com',
  },
  {
    id: 10043,
    name: 'Matthew Carter',
    role: 'DISCIPLINE',
    email: 'matthew.carter@example.com',
  },
  {
    id: 10044,
    name: 'Grace Mitchell',
    role: 'USER',
    email: 'grace.mitchell@example.com',
  },
  {
    id: 10045,
    name: 'Sebastian Perez',
    role: 'MIS',
    email: 'sebastian.perez@example.com',
  },
  {
    id: 10046,
    name: 'Emily Roberts',
    role: 'CASHIER',
    email: 'emily.roberts@example.com',
  },
  {
    id: 10047,
    name: 'Aiden Turner',
    role: 'PROGRAM HEAD',
    email: 'aiden.turner@example.com',
  },
  {
    id: 10048,
    name: 'Mila Phillips',
    role: 'REGISTRAR',
    email: 'mila.phillips@example.com',
  },
  {
    id: 10049,
    name: 'Owen Campbell',
    role: 'USER',
    email: 'owen.campbell@example.com',
  },
  {
    id: 10050,
    name: 'Victoria Parker',
    role: 'PURCHASING',
    email: 'victoria.parker@example.com',
  },
];

export { columns, users };
