import React from 'react';

const columns = [
  { name: 'ID', uid: 'id', sortable: true },
  { name: 'NAME', uid: 'name', sortable: true },
  { name: 'EMAIL', uid: 'email', sortable: true },
  { name: 'ROLE', uid: 'role', sortable: true },
  { name: 'SET ROLE', uid: 'set role', sortable: true },
];

const users = [
  {
    id: 1,
    name: 'Tony Reichert',
    role: 'USER',
    email: 'tony.reichert@example.com',
  },
  {
    id: 2,
    name: 'Zoey Lang',
    role: 'PROGRAM HEAD',
    email: 'zoey.lang@example.com',
  },
  {
    id: 3,
    name: 'Jane Fisher',
    role: 'LIBRARIAN',
    email: 'jane.fisher@example.com',
  },
  {
    id: 4,
    name: 'William Howard',
    role: 'REGISTRAR',
    email: 'william.howard@example.com',
  },
  {
    id: 5,
    name: 'Kristen Copper',
    role: 'GUIDANCE',
    email: 'kristen.cooper@example.com',
  },
  {
    id: 6,
    name: 'Brian Kim',
    role: 'MIS',
    email: 'brian.kim@example.com',
    status: 'Active',
  },
  {
    id: 7,
    name: 'Michael Hunt',
    role: 'CASHIER',
    email: 'michael.hunt@example.com',
  },
  {
    id: 8,
    name: 'Samantha Brooks',
    role: 'DISCIPLINE',
    email: 'samantha.brooks@example.com',
  },
  {
    id: 9,
    name: 'Frank Harrison',
    role: 'USER',
    email: 'frank.harrison@example.com',
  },
  {
    id: 10,
    name: 'Emma Adams',
    role: 'PURCHASING',
    email: 'emma.adams@example.com',
  },
  {
    id: 11,
    name: 'Brandon Stevens',
    role: 'LIBRARIAN',
    email: 'brandon.stevens@example.com',
  },
  {
    id: 12,
    name: 'Megan Richards',
    role: 'GUIDANCE',
    email: 'megan.richards@example.com',
  },
  {
    id: 13,
    name: 'Oliver Scott',
    role: 'MIS',
    email: 'oliver.scott@example.com',
  },
  {
    id: 14,
    name: 'Grace Allen',
    role: 'PROGRAM HEAD',
    email: 'grace.allen@example.com',
  },
  {
    id: 15,
    name: 'Noah Carter',
    role: 'CASHIER',
    email: 'noah.carter@example.com',
  },
  {
    id: 16,
    name: 'Ava Perez',
    role: 'USER',
    email: 'ava.perez@example.com',
  },
  {
    id: 17,
    name: 'Liam Johnson',
    role: 'REGISTRAR',
    email: 'liam.johnson@example.com',
  },
  {
    id: 18,
    name: 'Sophia Taylor',
    role: 'DISCIPLINE',
    email: 'sophia.taylor@example.com',
  },
  {
    id: 19,
    name: 'Lucas Harris',
    role: 'PURCHASING',
    email: 'lucas.harris@example.com',
  },
  {
    id: 20,
    name: 'Mia Robinson',
    role: 'USER',
    email: 'mia.robinson@example.com',
  },
  {
    id: 21,
    name: 'Ella Martinez',
    role: 'GUIDANCE',
    email: 'ella.martinez@example.com',
  },
  {
    id: 22,
    name: 'Ethan Anderson',
    role: 'LIBRARIAN',
    email: 'ethan.anderson@example.com',
  },
  {
    id: 23,
    name: 'Avery Thomas',
    role: 'DISCIPLINE',
    email: 'avery.thomas@example.com',
  },
  {
    id: 24,
    name: 'Isabella Jackson',
    role: 'USER',
    email: 'isabella.jackson@example.com',
  },
  {
    id: 25,
    name: 'Mason White',
    role: 'MIS',
    email: 'mason.white@example.com',
  },
  {
    id: 26,
    name: 'Harper Harris',
    role: 'CASHIER',
    email: 'harper.harris@example.com',
  },
  {
    id: 27,
    name: 'Logan Martin',
    role: 'PROGRAM HEAD',
    email: 'logan.martin@example.com',
  },
  {
    id: 28,
    name: 'Aria Garcia',
    role: 'REGISTRAR',
    email: 'aria.garcia@example.com',
  },
  {
    id: 29,
    name: 'James Lee',
    role: 'USER',
    email: 'james.lee@example.com',
  },
  {
    id: 30,
    name: 'Charlotte Clark',
    role: 'PURCHASING',
    email: 'charlotte.clark@example.com',
  },
  {
    id: 31,
    name: 'Henry Lewis',
    role: 'GUIDANCE',
    email: 'henry.lewis@example.com',
  },
  {
    id: 32,
    name: 'Amelia Walker',
    role: 'LIBRARIAN',
    email: 'amelia.walker@example.com',
  },
  {
    id: 33,
    name: 'Jack Young',
    role: 'DISCIPLINE',
    email: 'jack.young@example.com',
  },
  {
    id: 34,
    name: 'Scarlett Hall',
    role: 'USER',
    email: 'scarlett.hall@example.com',
  },
  {
    id: 35,
    name: 'Leo Allen',
    role: 'MIS',
    email: 'leo.allen@example.com',
  },
  {
    id: 36,
    name: 'Chloe King',
    role: 'CASHIER',
    email: 'chloe.king@example.com',
  },
  {
    id: 37,
    name: 'Benjamin Wright',
    role: 'PROGRAM HEAD',
    email: 'benjamin.wright@example.com',
  },
  {
    id: 38,
    name: 'Sofia Scott',
    role: 'REGISTRAR',
    email: 'sofia.scott@example.com',
  },
  {
    id: 39,
    name: 'Lucas Green',
    role: 'USER',
    email: 'lucas.green@example.com',
  },
  {
    id: 40,
    name: 'Zoe Adams',
    role: 'PURCHASING',
    email: 'zoe.adams@example.com',
  },
  {
    id: 41,
    name: 'Daniel Nelson',
    role: 'GUIDANCE',
    email: 'daniel.nelson@example.com',
  },
  {
    id: 42,
    name: 'Lily Baker',
    role: 'LIBRARIAN',
    email: 'lily.baker@example.com',
  },
  {
    id: 43,
    name: 'Matthew Carter',
    role: 'DISCIPLINE',
    email: 'matthew.carter@example.com',
  },
  {
    id: 44,
    name: 'Grace Mitchell',
    role: 'USER',
    email: 'grace.mitchell@example.com',
  },
  {
    id: 45,
    name: 'Sebastian Perez',
    role: 'MIS',
    email: 'sebastian.perez@example.com',
  },
  {
    id: 46,
    name: 'Emily Roberts',
    role: 'CASHIER',
    email: 'emily.roberts@example.com',
  },
  {
    id: 47,
    name: 'Aiden Turner',
    role: 'PROGRAM HEAD',
    email: 'aiden.turner@example.com',
  },
  {
    id: 48,
    name: 'Mila Phillips',
    role: 'REGISTRAR',
    email: 'mila.phillips@example.com',
  },
  {
    id: 49,
    name: 'Owen Campbell',
    role: 'USER',
    email: 'owen.campbell@example.com',
  },
  {
    id: 50,
    name: 'Victoria Parker',
    role: 'PURCHASING',
    email: 'victoria.parker@example.com',
  },
];

export { columns, users };
